### ISSUE TITLE
Support for localized date and time formats

### ISSUE THREAD

**Issue by padde** [padde/calendar_translations#3]
https://github.com/lau/calendar/commit/b8591e18e4087f2ba927193a8de57f6aabb297f1 introduced the possibility to use localized date and time formats with the `%x` and `%X` format strings. We should reflect that here.

**Comment by lau** [comment]
That would be nice. Also the date and time together (`%c`) would be useful.

**Comment by lau** [comment]
Does rails i18n have support for just time without a date? E.g. `%X` or "13:52:58". If not, maybe it can be left out for now. Maybe at some point we can get the data from somewhere else if necessary.

But either way getting support for %x and %c would be great.

**Comment by lau** [comment]
The function for date and time together will be called `date_time_format`

**Comment by padde** [comment]
rails-i18n has these formats predefined which we can use (examples for `en`):

https://github.com/svenfuchs/rails-i18n/blob/1a51482a3fc320bba5f71005651c291d71ccd6fb/rails/locale/en.yml#L204-L210

``` yaml
  date:
    formats:
      default: "%Y-%m-%d"
      long: "%B %d, %Y"
      short: "%b %d"
```

and these:

https://github.com/svenfuchs/rails-i18n/blob/1a51482a3fc320bba5f71005651c291d71ccd6fb/rails/locale/en.yml#L204-L210

``` yaml
  time:
    formats:
      default: "%a, %d %b %Y %H:%M:%S %z"
      long: "%B %d, %Y %H:%M"
      short: "%d %b %H:%M"
```

However all of these are the base for some helper functions that take options such as `I18n. localize(:de, date, :long)`, not for placeholders like `%x`. Maybe you can take a quick look and see if you find others that might be worth adding before I start implementing new translations.

Sure, I can add `date_time_format` as well, but I'm not sure any of the above formats from rails-i18n will match the exact requirements. The most natural choice in my opinion would be `time.formats.long` but it does not include seconds. We can also use `time.formats.default` but it includes the weekday and time zone on top. Strange actually that there's no format for just date + time ;-) We could also use `time.formats.long` and add the seconds manually by looking at the format used in `time.formats.default`. Which one would you prefer?

The current version of calendar also defines `%c` as `%a %b %e %T %Y`, which does not include time at all. Is it correct that you are planning to change this?

rails-i18n also translates strings for "am" and "pm", might be interesting as well. Note that languages that use the 24-hour clock don't have any string for am/pm defined, so I guess `%p` and `%P` would just return an empty string for these languages.

**Comment by padde** [comment]
Of course `%a %b %e %T %Y` includes time via `%T`, sorry, I missed that. But shouldn't the year come before the time?

**Comment by lau** [comment]
It is OK that it does not match %c exactly for now. Let us go with the "long" format for both date and date time.

Eventually it would be good if we could use the data used by most Linux distributions. But I haven't found it in plaintext format yet.

**Comment by lau** [comment]
By the way I have just released Calendar 0.12.2

**Comment by lau** [comment]
For now, am/pm will just be "am"/"pm" no matter the language like it is today in Calendar. It is mostly used by English speaking countries anyway. Maybe in the future if someone needs am/pm to be translated I can look at integrating support for that in Calendar.

**Comment by padde** [comment]
@lau I think for date_format the `date.formats.default` format would be more useful.

Good idea to look at the UNIX/Linux locale definitions.

Have you seen http://cldr.unicode.org/ yet? Looks like they have everything in machine readable format. Maybe we can generate the translations directly from the CLDR database. Maybe this could even be a library on its own, providing all kinds of translations from CLDR. calendar_translations then would be just a thin wrapper around that.

**Comment by padde** [comment]
@lau for `:en` you example for `time_format` is `%H:%M:%S`, but I don't see how this would differ between languages. If I understand correctly, the main difference is that some languages use the 12-hour-clock but only in the hour/minute variant, not with hours/minutes/seconds. For example, I have never seen something like "08:34:50 am" anywhere.

For now, I have implemented the same translation `%H:%M:%S` for every language, but that somehow defeats the purpose of having translations. Maybe we should switch to hour/minute here? On the other hand, that feels like it would be on a different level than date_format which seems wrong to me.

I think this is a sign that there are incredibly many variations on each format, even within a single language. All of them are useful in certain cases. I am thinking maybe adding full fledged translatable date and time formats should not be considered part of a date/time library, but rather part of an internationalization library that just happens to provide date/time formats based on locale and options. It's then up to the user to take that format and stick it into the date/time library.

**Comment by lau** [comment]
Hi Patrick. Nice work. I haven't had time to look respond to the PR or all your comments yet. An example is dots between the numbers instead of colon. E.g. 8.34 instead of 8:34 is common in Denmark. So if you use :da it would use that. Also 12 hour vs 24 hour as you write.

But hopefully if we get another source that aligns more with the Linux formats, we can get the formats for time without date too. For now, %H:%M:%S as a default is fine since we don't have the data.

**Comment by padde** [comment]
I think the CLDR database is as good as it gets. It has many formats and languages, is updated regularly including a peer review and the corresponding formats for different languages seem to match up really well. Apple for example seems to use it to generate translations for their products so they have some pressure to get things right.

Also, the data is in XML format. JSON is available as well, which is just generated from the official XML source. I don't like the idea of having to parse the binary linux locale data.

I haven't looked into licensing very thoroughly yet, but it seems they are using some kind of modified MIT license or so: http://unicode.org/copyright.html
